/* const.h */

#ifndef     _CONST_H_
#define     _CONST_H_

#define     TRUE    	1
#define 	FALSE		0

#define 	ENABLE  	1	
#define 	DISABLE		0	
#define     _ENABLE 	0	
#define 	_DISABLE	1   

#define     HIGH	 	1
#define 	LOW     	0
#define     ON 			1
#define     OFF			0 

#define     Int_Level_Act 	0  
#define     Int_Edge_Act 	1	

#define     Clrbyte			0x00    
#define     Dontcare		0xFF 

#define     SUBNETADDR      0x00          

typedef unsigned char uchar;
typedef unsigned int uint;

#endif



